micp_localization:
  ros__parameters:

    # required
    base_frame: base_footprint
    map_frame: map
    odom_frame: odom_combined

    # rate of broadcasting tf transformations
    tf_rate: 50.0

    micp:
      # merging on gpu or cpu
      combining_unit: cpu
      # maximum number of correction steps per second
      # lower this to decrease the correction speed but save energy 
      corr_rate_max: 100.0
      
      # adjust max distance dependend of the state of localization
      adaptive_max_dist: True # enable adaptive max dist

      # DEBUGGING   
      # corr = correspondences
      viz_corr: True
      # corr = correction
      print_corr_rate: False
      disable_corr: False

      # initial pose changes
      trans: [0.0, 0.0, 0.0]
      rot: [0.0, 0.0, 0.0] # euler angles (3) or quaternion (4) 

    # describe your sensor setup here
    sensors: # list of range sensors - at least one is required
      velodyne:
        topic: velodyne/points
        # topic_type: sensor_msgs/msg/PointCloud2
        type: spherical
        model:
          range_min: 0.5
          range_max: 130.0
          phi_min: -0.261799067259
          phi_inc: 0.03490658503988659
          phi_n: 16
          theta_min: -3.14159011841
          theta_inc: 0.01431249500496489 # (2*pi)/439 instead of (2*pi)/440 
          theta_n: 440
        micp:
          max_dist: 2.0
          adaptive_max_dist_min: 0.15
          backend: embree
      wheels: # pull robot to the mesh
        ranges: [0.2, 0.2, 0.2, 0.2]
        type: ondn
        frame: base_footprint
        model:
          width: 4
          height: 1
          range_min: 0.0
          range_max: 10.0
          origs: [ 0.15,  0.18,  0.2, # front left 
                   0.15, -0.18,  0.2, # front right
                  -0.15,  0.18,  0.2, # rear left
                  -0.15, -0.18,  0.2] # rear right
          dirs:  [ 0.0,  0.0, -1.0,
                   0.0,  0.0, -1.0,
                   0.0,  0.0, -1.0,
                   0.0,  0.0, -1.0]
        micp:
          max_dist: 1.0
          adaptive_max_dist_min: 0.2
          weight: 1.0
          backend: optix  