rmcl_pcl_conversion:
  ros__parameters:
    use_sim_time: True
    debug_cloud: True
    model:
      range_min: 0.3
      range_max: 130.0
      phi_min: -0.261799067259
      phi_inc: 0.03490658503988659
      phi_n: 16
      theta_min: -3.14159011841
      theta_inc: 0.01431249500496489 # (2*pi)/439 instead of (2*pi)/440 
      theta_n: 440